name: Continuous integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache Go modules
        uses: actions/cache@v2.1.6
        id: go-mod-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: make download

      - name: Lint
        run: |
          result=$(make lint)
          echo $result
          [ -n "$(echo "$result" | grep 'diff -u')" ] && exit 1 || exit 0

      - name: Build
        run: make build
